package ru.itis.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class DeviceTokenDto {
    @NotBlank(message = "The Device Token is required")
    @Size(min = 100, max = 255, message = "Device token length must be between 100 and 255 characters")
    @Pattern(regexp = "^[A-Za-z0-9+/=]+$", message = "Device token must be in Base64 format")
    @Schema(
            description = "A unique identifier for the device, used to send push notifications. It is generated by Firebase Cloud Messaging (FCM).",
            example = "fGh5JkLmN1oPqR2sTuVwXyZaBcDeFgHiJkLmN1oPqR2sTuVwXyZaBcDeFgHiJkLmN1oPqR2sTuVwXyZaBcDeFgHiJkLmN1oPqR2sTuVwXyZaBcDeFg=="
    )
    private String deviceToken;
}
